package com.wolf.camp.model;

// Generated May 5, 2015 8:59:40 PM by Hibernate Tools 4.3.1

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OrderBy;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Camp generated by hbm2java
 */
@Entity
@Table(name = "camp", catalog = "camp")
public class Camp implements java.io.Serializable {

	private Integer id;
	private Season season;
	private Integer count;
	private String email;
	private String locationOrigin;
	private String locationDestination;
	private List<Person> personList;
	
	//TODO: Add a person list model somewhat after season/items

	public Camp() {
	}

	public Camp(Season season, Integer count, String email, String locationOrigin, String locationDestination) {
		this.season = season;
		this.count = count;
		this.email = email;
		this.locationOrigin = locationOrigin;
		this.locationDestination = locationDestination;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "season_id")
	public Season getSeason() {
		return this.season;
	}

	public void setSeason(Season season) {
		this.season = season;
	}

	@Column(name = "count")
	public Integer getCount() {
		return this.count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

	@Column(name = "email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}


	@Column(name = "location_origin")
	public String getLocationOrigin() {
		return locationOrigin;
	}

	public void setLocationOrigin(String locationOrigin) {
		this.locationOrigin = locationOrigin;
	}

	@Column(name = "location_destination")
	public String getLocationDestination() {
		return locationDestination;
	}

	public void setLocationDestination(String locationDestination) {
		this.locationDestination = locationDestination;
	}

	@ManyToMany
	
	  @JoinTable(
		      name="CAMP_PERSON",
		      joinColumns={@JoinColumn(name="CAMP_ID", referencedColumnName="ID", nullable = false, updatable = true)},
		      inverseJoinColumns={@JoinColumn(name="PERSON_ID", referencedColumnName="ID", nullable = false, updatable = true)})
	@OrderBy("id")
	public List<Person> getPersonList() {
		return personList;
	}

	public void setPersonList(List<Person> personList) {
		this.personList = personList;
	}
	
	
	

}
